name: Main Pipeline

# This is a pre-NX workflow. Everything is checked for format, linting and type safety. Everything
# also requires a build step before each kind of test.
#
# NX integration and/or other optimizations will happen separately.

on:
  pull_request_target:

jobs:
  setup:
    name: pnpm install ðŸ› ï¸
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'
          cache: 'pnpm'

      - uses: actions/cache@v4
        id: node-modules-cache
        with:
          path: node_modules
          key: ${{ runner.os }}-node-modules-pnpm-${{ hashFiles('pnpm-lock.yaml') }}

      - if: steps.node-modules-cache.outputs.cache-hit != 'true'
        run: pnpm i --prefer-offline --frozen-lockfile

  license-check:
    name: License Check ðŸ“„
    runs-on: ubuntu-latest
    needs: setup
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v4

      - uses: dorny/paths-filter@v2
        id: changes
        with:
          filters: |
            lock:
              - 'pnpm-lock.yaml'

      - uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'

      - uses: actions/cache@v4
        if: steps.filter.outputs.lock == 'true'
        with:
          path: node_modules
          key: ${{ runner.os }}-node-modules-pnpm-${{ hashFiles('pnpm-lock.yaml') }}

      - if: steps.filter.outputs.lock == 'true'
        run: >
          echo "In case of error, please see ./CONTRIBUTING.md"
          pnpx license-checker \
          --summary \
          --production \
          --relativeLicensePath \
          --onlyAllow 'MIT;Apache-2.0;ISC;BSD-3-Clause;BSD-2-Clause;MIT*;Apache 2.0;Unlicense;Unlicensed;:CC0-1.0;CC-BY-4.0;WTFPL;0BSD;UNLICENSED;Python-2.0;MPL-2.0;CC-BY-3.0;CC0-1.0'

  format:
    name: Format check ðŸŽ¨
    runs-on: ubuntu-latest
    needs: setup
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'

      - uses: actions/cache@v4
        with:
          path: node_modules
          key: ${{ runner.os }}-node-modules-pnpm-${{ hashFiles('pnpm-lock.yaml') }}

      - run: pnpm format:check

  build:
    name: Build ðŸ“¦
    runs-on: ubuntu-latest
    timeout-minutes: 15
    needs: setup
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'

      - uses: actions/cache@v4
        with:
          path: node_modules
          key: ${{ runner.os }}-node-modules-pnpm-${{ hashFiles('pnpm-lock.yaml') }}

      - run: pnpm build:all

  type-check:
    name: Type Check ðŸ”·
    runs-on: ubuntu-latest
    needs: build
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'

      - uses: actions/cache@v4
        with:
          path: node_modules
          key: ${{ runner.os }}-node-modules-pnpm-${{ hashFiles('pnpm-lock.yaml') }}

      - run: pnpm build:all
      - run: pnpm typecheck

  lint:
    name: Lint ðŸŽ¨
    runs-on: ubuntu-latest
    needs: build
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'

      - uses: actions/cache@v4
        with:
          path: node_modules
          key: ${{ runner.os }}-node-modules-pnpm-${{ hashFiles('pnpm-lock.yaml') }}

      - run: pnpm build:all
      - run: pnpm lint:check

  test:
    name: Test ðŸ§ª
    runs-on: ubuntu-latest
    timeout-minutes: 15
    needs: build
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'

      - uses: actions/cache@v4
        with:
          path: node_modules
          key: ${{ runner.os }}-node-modules-pnpm-${{ hashFiles('pnpm-lock.yaml') }}

      - run: pnpm build:all
      - run: pnpm test:unit:all
